name: Artifact links comments creator
on:
  workflow_run:
    workflows: ["PR"]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: Add artifact links to PR and issues
    runs-on: ubuntu-latest
    steps:
      - name: Get information about the original PR
        uses: potiuk/get-workflow-origin@v1_5
        id: get-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
      - name: Add artifact links to PR and issues
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: "**Do you want to test this code? Here you have an automated build:**"
          suffix: "_**WARNING:** It may be unstable. Use only for testing!_"
          format: name
          addTo: pull
