name: CI

on: 
  workflow_call:

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest

          - name: macOS
            os: macos-13

          - name: Windows
            os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfreetype6-dev libcairo2-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-13'
        run: |
          brew install pkg-config freetype cairo

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install freetype
          choco install cairo
          choco install getopt

      - name: Build the tools
        if: matrix.os != 'windows-latest'
        run: make all

      - name: Build the tools (Windows)
        if: matrix.os == 'windows-latest'
        run: msbuild 'visual-studio/Baseflight blackbox-tools.sln' /p:Configuration=Release

      - name: Publish build artifacts
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Blackbox tools artifacts ${{matrix.name}}
          path: obj/*
          retention-days: 60

      - name: Publish build artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: Blackbox tools artifacts ${{matrix.name}}
          path: dist/win32/*
          retention-days: 60
