name: CI

on: 
  workflow_call:

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest

          - name: macOS
            os: macos-12

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfreetype6-dev libcairo2-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-12'
        run: |
          brew install pkg-config freetype cairo

      - name: Build the tools
        run: make all

      - name: Publish build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Blackbox tools artifacts ${{matrix.name}}
          path: obj/*
          retention-days: 60
