name: CI

on: 
  workflow_call:

jobs:
  build:
    name: Build (${{ matrix.name }})
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest

          - name: macOS
            os: macos-13

          - name: Windows
            os: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libfreetype6-dev libcairo2-dev

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-13'
        run: |
          brew install pkg-config freetype cairo

      - name: Install msys2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2
        run: |
          pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-freetype mingw-w64-x86_64-cairo mingw-w64-x86_64-gcc

      - name: Build the tools
        if: matrix.os != 'windows-latest'
        run: make all

      - name: Build the tools (Windows)
        if: matrix.os == 'windows-latest'
        shell: msys2
        run: make all

      - name: Publish build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Blackbox tools artifacts ${{matrix.name}}
          path: obj/*
          retention-days: 60
